blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='main'),

    path('cats', views.ListKittens.as_view(), name='cat'),
    path('dogs', views.ListPupies.as_view(), name='dog'),
    path('about', views.TeamList.as_view(), name='about'),
    path('questions', views.OftenQuest, name='quest'),

    path('cats/<int:pk>/', views.DetailKit.as_view(), name='cat_list'),
    path('dogs/<int:pk>/', views.DetailPup.as_view(), name='dog_list'),

    path('addcat', views.AddCat, name='addcat'),
    path('adddog', views.AddDog, name='adddog'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('register/', views.Register.as_view(), name='register')
]

blog/models.py
from django.db import models


# class Users(models.Model):
#     name = models.CharField(max_length=20)
#     email = models.EmailField()
#     password = models.CharField(max_length=50)
from django.urls import reverse


class Team(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    job = models.CharField(max_length=100)
    image = models.ImageField(upload_to='articles/')

    def __str__(self):
        return self.name


class Breed_cat(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name


class Breed_dog(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name


class Sex(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name


class Cat(models.Model):
    text = models.TextField()
    sex = models.ForeignKey(Sex, related_name='post_cat', on_delete=models.CASCADE)
    breed = models.ForeignKey(Breed_cat, related_name='post', on_delete=models.SET_NULL, null=True)
    color = models.CharField(max_length=20)
    age = models.CharField(max_length=20)
    img = models.ImageField(upload_to='articles/')

    def get_absolute_url(self):
        return reverse('cat_list', kwargs={'pk': self.id})


class Dog(models.Model):
    text = models.TextField()
    sex = models.ForeignKey(Sex, related_name='post_dog', on_delete=models.CASCADE)
    breed = models.ForeignKey(Breed_dog, related_name='post', on_delete=models.SET_NULL, null=True)
    color = models.CharField(max_length=20)
    age = models.CharField(max_length=20)
    img = models.ImageField(upload_to='articles/')

    def get_absolute_url(self):
        return reverse('dog_list', kwargs={'pk': self.id})

blog/forms.py
from django import forms
from .models import *


class AddCatForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sex'].empty_label = 'Не выбран'
        self.fields['breed'].empty_label = 'Не выбрана'

    class Meta:
        model = Cat
        fields = '__all__'


class AddDogForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sex'].empty_label = 'Не выбран'
        self.fields['breed'].empty_label = 'Не выбрана'

    class Meta:
        model = Dog
        fields = '__all__'

blog/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView

from blog.models import Cat, Dog, Team
from blog.forms import AddCatForm, AddDogForm


def home(request):
    return render(request, 'blog/main.html')


class ListKittens(ListView):
    model = Cat
    queryset = Cat.objects.all()


class ListPupies(ListView):
    model = Dog
    queryset = Dog.objects.all()


class DetailKit(View):
    def get(self, request, pk):
        data = Cat.objects.get(id=pk)
        return render(request, 'blog/pet.html', {'pet': data})


class DetailPup(View):
    def get(self, request, pk):
        data = Dog.objects.get(id=pk)
        return render(request, 'blog/pet.html', {'pet': data})


def AboutUs(request):
    return render(request, 'blog/about_us.html')


def OftenQuest(request):
    return render(request, 'blog/often_questions.html')


class TeamList(ListView):
    model = Team
    queryset = Team.objects.all()
    template_name = 'blog/about_us.html'


def AddCat(request):
    if request.method == 'POST':
        form = AddCatForm(request.POST or None, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('cat')

    else:
        form = AddCatForm()
    return render(request, 'blog/addcat.html', {'form': form})


def AddDog(request):
    if request.method == 'POST':
        form = AddDogForm(request.POST or None, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('dog')

    else:
        form = AddDogForm()
    return render(request, 'blog/adddog.html', {'form': form})

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views import View


class Register(View):
    template_name = 'registration/register.html'

    def get(self, request):
        context = {
            'form': UserCreationForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Neucha&display=swap" rel="stylesheet">
        <meta charset="UTF-8">
        <title>{%block title%}{%endblock title%}</title>
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
        <link rel="stylesheet" href="{% static 'css/workcss.css' %}">

        

        <link href="https://fonts.googleapis.com/css?family=Abel|Advent+Pro|Alegreya|Alice|Amaranth|Arapey|Aref+Ruqaa|Bentham|Bubbler+One|Cantata+One|Chathura|Convergence|Domine|Droid+Serif|Gentium+Basic|Lato|Libre+Baskerville|Lora|Marvel|Merriweather|Nunito|Old+Standard+TT|Open+Sans|Oranienbaum|Oswald|Prata|Quicksand|Rufina|Ruluko|Rum+Raisin|Saira|Saira+Condensed|Saira+Extra+Condensed|Sansita|Snippet|Text+Me+One|Titillium+Web|Vidaloka|Wire+One" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    </head>
<body id="top" style="background: url({% static 'img/fon.png' %})">
    <header class="header">

        <div class="container">

            <a href="{% url 'main'%}"><span class="logo">Kennel</span></a>
            {% if user.is_authenticated %}
                <div class="btns">
                    {%block btn%}{%endblock btn%}
                    <a href="{% url 'logout' %}"><button class="login_button">{{ user }}</button></a>
                </div>
            {% else %}
                <div class="btns">
                    <a href="{% url 'login' %}"><button class="login_button">Войти</button></a>
                    <a href="{% url 'register'%}"><button class="login_button">Регистрация</button></a>
                </div>
            {% endif %}


        </div>

    </header>


    <div class="category-wrap">
        <h3>Куда направитесь?</h3>
        <ul>
          <li><a href="{% url 'dog'%}">Наши собачки</a></li>
          <li><a href="{% url 'cat'%}">Наши кошечки</a></li>
          <li><a href="{% url 'quest'%}">Частые вопросы</a></li>
          <li><a href="{% url 'about'%}">О нас</a></li>
        </ul>
    </div>
    {% block content%}{% endblock content%}
</body>
</html>

templates/blog/about_us.html
{% extends 'base.html'%}

{%block title%}О нас{%endblock title%}

{% block content%}
        <div class="container">
            <div class="main_us">
                <div class="text_us">
                    <p>Мы один из приютов города Новосибирск. Находимя по адресу @@@</p>
                    <p>Мы ухаживаем за каждой кошечкой или собачкой, которые к нам попадают, до тех пор, пока не найдём ему нового хозяйна.</p>
                    <p>В нашем приюте есть команда из 6-ти человек</p>
                    <p>Какими методами мы сейчас вам и расскажем.</p>
                </div>
            </div>
            
            <div class="main_us">
                <div class="text_us">
                    <h1>Питание</h1>
                    <p>Едут они 3 раза в день</p>
                    <p>Собак мы кормим данными элитными кормами, производимые за рубежом:</p>
                    <ul>
                        <li>Profine</li>
                        <li>Monge</li>
                        <li>Crockex Wellness</li>
                    </ul>
                    <p>Кошек же мы кормим этими элитными кормами производимыми за рубежом:</p>
                    <ul>
                        <li>Brit Care</li>
                        <li>Monge BWild</li>
                        <li>Savory</li>
                    </ul>
                </div>
            </div>

            <div class="main_us">
                <div class="text_us">
                    <h1>Уход</h1>
                    <p>Особый уход который мы проявляем нашим братьям меньшим:</p>
                    <ul>
                        <li>Мы гуляем с ними регулярно</li>
                        <li>Моем после каждой прогулки</li>
                        <li>Обеспечиваем медицинскую помощь</li>
                    </ul>
                    <p>Они живут в комфортных условиях для проживания:</p>
                    <ul>
                        <li>Для собак у нас имеются первоклассные вольеры</li>
                        <li>Для кошек у нас есть первоклассные коробки</li>
                        <li>Всё здание покрыто антиаллергенным покрытием</li>
                    </ul>
                </div>
            </div>

            <div class="main_us" style="border-bottom: 2px solid #e6007e;">
                <div class="text_us">
                    <h1>Команда</h1>

                    <div class='nachinka'>
                        <ul>
                            {% for item in team_list %}
                            <li>
                                <img src="{{item.image.url}}" alt="ОН не дал нам свой фото">
                                <p>{{item.name}} {{item.surname}}</p>
                                <span>{{item.job}}</span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

        </div>

    <div class="footer">

    </div>
{% endblock content%}

templates/blog/addcat.html
{% extends 'base.html'%}

{%block title%}Добавление{%endblock title%}


{% block content%}
<div class="container">
<div class="main">
    <div class="text_us">
    <h1>Добавление котика</h1>
    </div>
    <form action="{% url 'addcat'%}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        <div class="text_us">
            {% for field in form %}
            <div class="form-group">
                {{field.label_tag}}
                <div>{{field}}</div>
                {% if field.errors%}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{error}}
                </div>
                {% endfor %}
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="sub_button">Добавить</button>
        </div>
    </form>
</div>
</div>

{% endblock content%}

templates/blog/adddog.html
{% extends 'base.html'%}

{%block title%}Добавление{%endblock title%}


{% block content%}
<div class="container">
<div class="main">
    <div class="text_us">
    <h1>Добавление пёселя</h1>
    </div>
    <form action="{% url 'adddog'%}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        <div class="text_us">
            {% for field in form %}
            <div class="form-group">
                {{field.label_tag}}
                <div>{{field}}</div>
                {% if field.errors%}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{error}}
                </div>
                {% endfor %}
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="sub_button">Добавить</button>
        </div>
    </form>
</div>
</div>

{% endblock content%}

templates/blog/cat_list.html
{% extends 'base.html'%}
{%block title%}Кошечки{%endblock title%}

{%block btn%}
{%if user.is_superuser%}
    <a href="{% url 'addcat' %}"><button class="login_button">Добавить питомца</button></a>
{%endif%}
{%endblock btn%}

{% block content %}
        <h1 class="name_page">
            Н<br>
            а<br>
            ш<br>
            и<br>
            <br>
            к<br>
            о<br>
            ш<br>
            е<br>
            ч<br>
            к<br>
            и<br>

        </h1>


        
        <div class="container">

            {% for cat in cat_list %}
            <div id="containers">	
        
                <!-- Start	Product details -->
                    <div class="product-details">
                        
                        <!-- 	Product Name -->
                    <!-- <h1>Biru Putaran</h1> -->
                <!-- 		<span class="hint new">New</span> -->
                <!-- 		<span class="hint free-shipping">Free Shipping</span> -->
                <!-- 		the Product rating -->
                        
                    
                <!-- The most important information about the product -->
                        <p class="information">{{cat.text}}</p>



                <!-- 		Control -->
                <div class="control">
                    
                    <!-- Start Button buying -->
                    <a href="{{cat.get_absolute_url}}"><button class="btnq">
                    <!-- 		Buy Now / ADD to Cart-->
                        {% if cat.sex.slug == 'male'%}
                        <span class="buy">Хочу его</span>
                        {% else %}
                        <span class="buy">Хочу её</span>
                        {% endif %}
                    </button></a>
                        <!-- End Button buying -->
                    
                </div>
                            
                </div>
                    
                <!-- 	End	Product details   -->
                    
                    
                    
                <!-- 	Start product image & Information -->
                    
                <div class="product-image">
                    
                    <img src="{{cat.img.url}}" alt="Omar Dsoky">
                    
                <!-- 	product Information-->
                <div class="info">
                    <h2>Описание</h2>
                    <ul>
                        <li><strong>Пол: </strong>{{cat.sex}}</li>
                        <li><strong>Порода: </strong>{{cat.breed}}</li>
                        <li><strong>Окрас: </strong>{{cat.color}}</li>
                        <li><strong>Возраст: </strong>~ {{cat.age}}</li>
                    </ul>
                </div>
                </div>
                <!--  End product image  -->
            </div>
            {% endfor %}
        </div>
<div class="footer"></div>
{% endblock content%}

templates/blog/dog_list.html
{%extends 'base.html'%}

{%block title%}Собачки{%endblock title%}

{%block btn%}
{%if user.is_superuser%}
    <a href="{% url 'adddog' %}"><button class="login_button">Добавить питомца</button></a>
{%endif%}
{%endblock btn%}

{% block content%}
        <h1 class="name_page">
            Н<br>
            а<br>
            ш<br>
            и<br>
            <br>
            с<br>
            о<br>
            б<br>
            а<br>
            ч<br>
            к<br>
            и<br>

        </h1>


        
        <div class="container">

            {% for dog in dog_list%}
            <div id="containers">	
        
                <!-- Start	Product details -->
                    <div class="product-details">
                        <p class="information">{{dog.text}}</p>
                
                        
                        
                <!-- 		Control -->
                <div class="control">
                    
                    <!-- Start Button buying -->
                    <a href="{{dog.get_absolute_url}}"><button class="btnq">
                    <!-- 		Buy Now / ADD to Cart-->
                        {% if dog.sex.slug == 'male'%}
                        <span class="buy">Хочу его</span>
                        {% else %}
                        <span class="buy">Хочу её</span>
                        {% endif %}
                    </button></a>
                        <!-- End Button buying -->
                    
                </div>
                            
                </div>
                    
                <!-- 	End	Product details   -->
                    
                    
                    
                <!-- 	Start product image & Information -->
                    
                <div class="product-image">
                    
                    <img src="{{dog.img.url}}" alt="Omar Dsoky">
                <!-- 	product Information-->
                <div class="info">
                    <h2>Описание</h2>
                    <ul>
                        <li><strong>Пол: </strong>{{dog.sex}}</li>
                        <li><strong>Порода: </strong>{{dog.breed}}</li>
                        <li><strong>Окрас: </strong>{{dog.color}}</li>
                        <li><strong>Возраст: </strong>~ {{dog.age}}</li>
                    </ul>
                </div>
                </div>
                <!--  End product image  -->
            </div>
            {% endfor %}
        </div>  
         <!-- конец conteiner  -->

<div class="footer">
</div>
{% endblock content%}

templates/blog/main.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
    <div class="container">
        <div class="main">
            <div class="text">
                <h1></h1>
                <p>Мы один из приютов города Новосибирск.</p>
                <p>Мы ухаживаем за каждой кошечкой или собачкой, которые к нам попадают, до тех пор, пока не найдём ему нового хозяйна.</p>
                <p>Хочешь узнать больше о наших питомцах?</p>
            </div>
            <div class="group_cards">
                <div class="card">
                    <img src="{% static 'img/pesek.jpg' %}" alt="Пёсик" style="width:100%">
                    <h1>Наши пёсики</h1>
                    <p>Верные и добрые друзья, готовые провести с вами вечер</p>
                    <a href="{% url 'dog'%}"><p><button>Хочу их</button></p></a>
                </div>
                <div class="card">
                    <img src="{% static 'img/kit.jpg' %}" alt="Котейка" style="width:100%">
                    <h1>Наши котики</h1>
                    <p>Ласковые и милые друзья, готовые лежать с вами целый день</p>
                    <a href="{% url 'cat' %}"><p><button>Хочу их</button></p></a>
                </div>
            </div>
        </div>
    </div>
   <div class="footer">

    </div>
{% endblock content %}

templates/blog/often_questions.html
{%extends 'base.html'%}

{%block title%}Вопросы{%endblock title%}

{%block content%}
    <div class="container">


        <div class="main_us">
            <div class="text_us">
                <p>На этой странице находятся ответы на часто задаваемые вопросы нашим сотрудникам.</p>
                <p>При вознекновении иных вопросов, свяжитесь с нами по контактам внизу страницы.</p>
            </div>
        </div>
        

        <div class="main_us">
            <div class="text_us">
                <h3>Как вы ухаживаете за животными?</h3>
                <p>Всё о нашей организации и о том как мы ухаживаем за питомцами, вы можете узнать на странице <a href="{% url 'about'%}">О нас</a></p>
            </div>
        </div>


        <div class="main_us" style="border-bottom: 2px solid #e6007e;">
            <div class="text_us">
                <h3>Можем ли мы быть уверены в том, что получим здорового питомца?</h3>
                <p>Наш приют сотрудничает с вет. клиникой @@@. При любых отклонениях в поведении животных, мы обращаемя к ветеринарам.</p>
                <p>Также мы соблюдаем чистоту в нашем приюте, поэтому вероятность заболеть очень мала.</p>
            </div>
        </div>
    </div>

   <div class="footer">

    </div>
{% endblock content%}

templates/blog/pet.html
{%extends 'base.html'%}

{%block title%}Питомец{%endblock title%}

{%block content%}
        <div class="container">
            
            <div class="pos_img">
                <p class="fig"><img class="round_img" src="{{pet.img.url}}" alt="netu peseka"></p>
            </div>
            <div class="main" style="border-top: 2px solid #e6007e; position: relative; bottom: 128px;">
                <div class="text_us" style="margin-bottom: 50px; margin-top: 50px;">
                    <ul>
                        <li><strong>Пол: </strong>{{pet.sex}}</li>
                        <li><strong>Порода: </strong>{{pet.breed}}</li>
                        <li><strong>Окрас: </strong>{{pet.color}}</li>
                        <li><strong>Возраст: </strong>~ {{pet.age}}</li>
                    </ul>
                </div>
                <div class="text_us">{{pet.text}}</div>
                <button class="btnq" style="margin-left: 50px; margin-top: 20px; margin-bottom: 20px; background: violet;">
                        {% if pet.sex.slug == 'male'%}
                        <span class="buy">Дайте мне его</span>
                        {% else %}
                        <span class="buy">Дайте мне её</span>
                        {% endif %}
                </button>
            </div>
        </div>
        <div class="footer">
        </div>
{% endblock content%}